### PR TITLE
Add April 2017 presentation on Consul & Vault deployment

### PR DESCRIPTION
**Pull request by misham**

### CODE REVIEW

**Review by svanzoest — APPROVED** [review]

**Comment by svanzoest** [comment]
@misham I just realized you may have forgotten to add the PDF, can you provide another commit?

**Comment by misham** [comment]
Looks like I messed up the link to the PDF.  Let me update that

**Comment by svanzoest** [comment]
Ahh.. I see.. easy enough to fix.

**Comment by misham** [comment]
Submitted #5 with the fix

**Pull request merged**
